# Generated by Django 5.0.6 on 2024-07-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
