# Generated by Django 5.0.6 on 2024-08-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0003_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
